version: '3.7'

networks:
  network:

volumes:
  postgres-data:

services:
  metabase:
    image: "metabase/metabase:v0.34.0"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase_user
      - MB_DB_PASS=metabase_password
      - MB_DB_HOST=postgres
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    networks:
      - network

  postgres:
    image: "postgres:12.1-alpine"
    environment:
      - PGDATA=/postgresql/data
      - POSTGRES_USER=metabase_user
      - POSTGRES_PASSWORD=metabase_password
      - POSTGRES_DB=metabase
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
    volumes:
      - postgres-data:/postgresql/data
    networks:
      - network
