version: '3.7'

networks:
  core:
    driver: overlay

volumes:
  mysql:
  wordpress:
  ftp-passwd:

services:
  mysql:
    image: ${MYSQL_IMAGE}
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress_database
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: example
    networks:
      - core

  wordpress:
    image: wordpress:5.1.1-php7.3-apache
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    volumes:
      - wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: wordpress_database
    networks:
      - core

  ftpd-server:
    image: ${FTP_IMAGE}
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    volumes:
      - wordpress:/home/ftp_user/
      - ftp-passwd:/etc/pure-ftpd/passwd
    environment:
      PUBLICHOST: "X.X.X.X"
      FTP_USER_NAME: ftp_user
      FTP_USER_PASS: example
      FTP_USER_HOME: /home/ftp_user
    ports:
      - 21:21
      - 30000-30009:30000-30009
    networks:
      - core
