version: '3.7'

networks:
  network:
    driver: overlay

volumes:
  postgres-data:
    driver: local

services:

  postgres:
    image: "postgres:11.4-alpine"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - 5436:5432
    volumes:
      - postgres-data:/postgresql/data
    environment:
      - PGDATA=/postgresql/data
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=gaewivan3aaq
      - POSTGRES_DB=test_database
    networks:
      - network
