version: '3.7'

networks:
  network:
    driver: overlay

services:
  memcached:
    image: "memcached:1.5.20-alpine"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - "11211:11211"
    networks:
      - network
