version: '3.7'

networks:
  network:
    driver: overlay

volumes:
  rethinkdb-data:

services:
  rethinkdb:
    image: "rethinkdb:2.4.0"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - rethinkdb-data:/data
    networks:
      - network
