version: '3.7'

networks:
  network:
    driver: overlay

services:

  cadvisor-exporter:
    image: "google/cadvisor:latest"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    command: -port=9080
    ports:
      - "9080:9080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - network

  node-exporter:
    image: "prom/node-exporter:v0.18.1"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    user: root
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - network

  blackbox-exporter:
    image: "prom/blackbox-exporter:v0.14.0"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - network

  nginx-exporter:
    image: "nginx/nginx-prometheus-exporter:0.4.1"
    command: -nginx.scrape-uri http://nginx:80/stub_status
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - "9113:9113"
    networks:
      - network

  postgres-exporter:
    image: "wrouesnel/postgres_exporter:v0.5.0"
    deploy:
      replicas: 1
    environment:
      - DATA_SOURCE_NAME=postgresql://user:password@postgres:5432/database?sslmode=disable
    networks:
      - network

  mysql-exporter:
    image: "prom/mysqld-exporter:v0.11.0"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      - DATA_SOURCE_NAME=root:password@(mysql:3306)/
    networks:
      - network

#  mongodb-exporter:
#    image: "mongodb_exporter"
#    deploy:
#      replicas: 1
#    environment:
#      - MONGODB_URL="mongodb://user:password@mongodb:27017/database",
#    networks:
#      - network

  elasticsearch-exporter:
    image: "justwatch/elasticsearch_exporter:1.0.2"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    command: '-es.uri=http://elasticsearch:9200'
    ports:
      - 9108:9108
    networks:
      - network

  redis-exporter:
    image: "oliver006/redis_exporter:v1.0.3-alpine"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      - REDIS_ADDR=redis://redis:6379
    networks:
      - network

  rabbitmq-exporter:
    image: "kbudde/rabbitmq-exporter:v1.0.0-RC6.1"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      - RABBIT_URL=http://rabbitmq:15672
      - RABBIT_USER=rabbit
      - RABBIT_PASSWORD=password
    networks:
      - network
