FROM grafana/grafana
LABEL maintainer="Denis Sventitsky <denis.sventitsky@gmail.com> / Twisted Fantasy <twisteeed.fantasy@gmail.com>"

COPY grafana/datasources /etc/grafana/datasources
COPY grafana/dashboards /etc/grafana/dashboards
COPY grafana/setup.sh /setup.sh
