version: "3.7"

networks:
  network:
    driver: bridge

volumes:
  pgadmin-data:


services:
  pgadmin:
    image: dpage/pgadmin4:4.12
    environment:
      PGADMIN_DEFAULT_EMAIL: system@test.com
      PGADMIN_DEFAULT_PASSWORD: I0Kk2JPNFumZExPu
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 80:80
    networks:
      - network
