route:
  repeat_interval: 2h
  receiver: mail-receiver
  routes:
    - match:
        alertname: nginx_down
      receiver: mail-receiver
    - match:
        alertname: high_host_cpu_utilisation
      receiver: critical-mail-receiver
    - match:
        alertname: low_disk_space
      receiver: critical-mail-receiver
    - match:
        alertname: low_ram_space
      receiver: critical-mail-receiver
    - match:
        alertname: unusual_network_throughput_in
      receiver: critical-mail-receiver
    - match:
        alertname: unusual_network_throughput_out
      receiver: critical-mail-receiver

receivers:
- name: 'mail-receiver'
  email_configs:
  - to: <to-email>
    from: <from-email>
    smarthost: <smtp:port>
    auth_username: "<user-name>"
    auth_identity: "<user-name>"
    auth_password: "<user-app-specific-password>"

- name: 'critical-mail-receiver'
  email_configs:
    - to: <to-email>
      from: <from-email>
      smarthost: <smtp:port>
      auth_username: "<user-name>"
      auth_identity: "<user-name>"
      auth_password: "<user-app-specific-password>"
