route:
  repeat_interval: 2h
  receiver: warning
  routes:
    - match:
        severity: warning
      receiver: warning

    - match:
        severity: critical
      receiver: critical

receivers:
- name: 'warning'
  email_configs:
  - to: <to-email>
    from: <from-email>
    smarthost: <smtp:port>
    auth_username: "<user-name>"
    auth_identity: "<user-name>"
    auth_password: "<user-app-specific-password>"

- name: 'critical'
  email_configs:
    - to: <to-email>
      from: <from-email>
      smarthost: <smtp:port>
      auth_username: "<user-name>"
      auth_identity: "<user-name>"
      auth_password: "<user-app-specific-password>"
