version: '3.7'

networks:
  network:
    driver: overlay

services:
    rabbitmq:
      image: "rabbitmq:3.7.15-alpine"
      deploy:
        replicas: 1
        placement:
          constraints: [node.role == manager]
      networks:
        - network
