version: '3.7'

networks:
  network:

services:
    rabbitmq:
      image: "rabbitmq:3.7.17-management-alpine"
      environment:
        RABBITMQ_DEFAULT_USER: rabbit
        RABBITMQ_DEFAULT_PASS: password
      ports:
        - "15672:15672"
      networks:
        - network
