version: '3.7'

networks:
  network:
    driver: overlay

volumes:
  mongodb-data:

services:
  mongodb:
    image: "mongo:4.1.13-bionic"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      MONGO_INITDB_ROOT_USERNAME: test_user
      MONGO_INITDB_ROOT_PASSWORD: test_password
    volumes:
      - mongodb-data:/data/db
    networks:
      - network

  mongodb-express:
    image: "mongo-express:0.49.0"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: test_password
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: test_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: test_password
    networks:
      - network
