version: '3.7'

networks:
  network:
    driver: overlay

volumes:
  elasticsearch-data:

services:
  elasticsearch:
    image: "elasticsearch:7.2.0"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - network
