version: '3.7'

networks:
  network:

volumes:
  elasticsearch-data:

services:
  elasticsearch:
    image: "elasticsearch:7.5.1"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
      - target: 9300
        published: 9300
        protocol: tcp
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - network
