version: '3.7'

networks:
  network:
    driver: bridge

volumes:
  mariadb-data:

services:
  mariadb:
    image: "mariadb:10.4.6-bionic"
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test_database
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=test_password
    ports:
      - 3336:3306
    networks:
      - network
