version: '3.6'

networks:
  network:
    driver: bridge

volumes:
  mariadb-data:
    driver: local

services:

  mariadb:
    build:
      context: ../
      dockerfile: dockerX/mariadb/Dockerfile
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Yi6vLzVYgoqIg89R
      - MYSQL_DATABASE=fomular_assistent_database
      - MYSQL_USER=fomular_assistent_user
      - MYSQL_PASSWORD=v9Lvu3qpnFoagie7
    ports:
      - 3336:3306
    networks:
      - network
