version: '3.7'

networks:
  network:

volumes:
  mysql-data:

services:
  mysql:
    image: "mysql:8.0.17"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test_database
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=test_password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - network
