version: '3.7'

networks:
  network:
    driver: overlay

volumes:
  mysql-data:

services:
  mysql:
    image: "mysql:8.0.16"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - network
