ARG IMAGE
FROM $IMAGE
LABEL maintainer="Denis Sventitsky <denis.sventitsky@gmail.com> / Twisted Fantasy <twisteeed.fantasy@gmail.com>"

WORKDIR /usr/src/app

CMD npm i && npm rebuild node-sass && npm start
