global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
      monitor: 'prometheus-grafana-exporter'
      branch: 'BRANCH'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
  - "rules/system/cpu.rules"
  - "rules/system/disk.rules"
  - "rules/system/ram.rules"
  - "rules/system/network.rules"
  - "rules/system/docker.rules"
  - "rules/services/ssl.rules"
  - "rules/services/nginx.rules"
  - "rules/services/postgres.rules"
  - "rules/services/mysql.rules"
  - "rules/services/mongodb.rules"
  - "rules/services/elasticsearch.rules"
  - "rules/services/redis.rules"
  - "rules/services/rabbitmq.rules"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'cadvisor'
    scrape_interval: 10s
    static_configs:
      - targets: ['cadvisor-exporter:9080']

  - job_name: 'node'
    scrape_interval: 30s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'nginx'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets: ['nginx:80']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement:  blackbox-exporter:9115

  - job_name: 'nginx-stub-status'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch-exporter:9108']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']

#  - job_name: 'spring-boot'
#    scrape_interval: 60s
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['backend:8080']
#    metric_relabel_configs:
#      - source_labels: [__name__]
#        target_label: __name__
#        replacement: "backend_${1}"
