#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE $TEST_DATABASE;
    CREATE USER $TEST_USER WITH PASSWORD '$TEST_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $TEST_DATABASE to $TEST_USER;

    CREATE DATABASE $TEST2_DATABASE;
    CREATE USER $TEST2_USER WITH PASSWORD '$TEST2_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $TEST2_DATABASE to $TEST2_USER;
EOSQL
