version: '3.7'

networks:
  network:
    driver: bridge

volumes:
  postgres-data:

services:
  postgres:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/postgresql/data
    networks:
      - network
