version: '3.7'

networks:
  network:
    driver: overlay

volumes:
  matomo-data:

services:
  matomo:
    image: "twistedfantasy:matomo"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    volumes:
      - matomo-data:/var/www/html/config:rw
    networks:
      - network
