version: '3.7'

networks:
  network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  portainer-data:
    driver: local

services:

  todo:
    image: ${PYTHON_IMAGE}
    command: >
      sh -c "cd /usr/src/todo/ &&
             pip install -r requirements.txt &&
             python3 /usr/src/scripts/systemuser.py &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    restart: on-failure
    env_file:
      - todo/develop.env
    ports:
      - 8000:8000
    volumes:
      - ../todo:/usr/src/todo/
      - /opt/pycharm-2018.1.3/debug-eggs/:/usr/src/pycharm/debug-eggs/
    depends_on:
      - postgres
      - redis
    networks:
      - network
