version: '3.7'

networks:
  network:

volumes:
  postgres-data:
  redis-data:
  portainer-data:

services:

  todo:
    image: ${PYTHON_IMAGE}
    command: bash -c "pip install -r requirements.txt &&
                      python3 manage.py migrate &&
                      python3 manage.py collectstatic --noinput &&
                      python3 manage.py runserver 0.0.0.0:8000"
    restart: on-failure
    env_file:
      - todo/develop.env
    ports:
      - 8000:8000
    volumes:
      - ../todo:/usr/src/todo/
    depends_on:
      - postgres
      - redis
    networks:
      - network
